name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Install Dependencies
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y software-properties-common make binutils perl libconfig-simple-perl libfile-find-rule-perl mtools dosfstools
      - run: sudo add-apt-repository -y ppa:tkchia/build-ia16 && sudo apt-get install -y gcc-ia16-elf nasm
      - run: perl make.pl build
      
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/master'
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "System Floppy"
          files: |
            build/system.img
